Repository one-acre-fund/ph-ee-connector-ams-paygops, pull requests merged in 2024-02, with the labels that each got.

#3 Rename Wallet Operator - SER-2208
  RELEASE_NOTES.md
  build.gradle
  src/main/java/org/mifos/connector/ams/paygops/camel/route/PaygopsRouteBuilder.java
  src/main/resources/application.yml
Labels: size/S

#4 add github actions
  .github/workflows/build.yaml
Labels: size/M

#6 fix github action bug
  .github/workflows/build.yaml
Labels: size/XS
